DEFAULT: #For this section ensure none of the keys are missing
  epochs: 50
  save_loc: ABC  #Empty save loc indicates no save location
  resume_loc: ABC #Empty resume loc indicates no need to resume
  save_freq: 10
  gpu_devices: [1,2,3]
  use_dataparallel: False
  location_mod: ABC
  random_seed: 2022
  
METRIC:
  subclass_type: mnist

MODEL:
  subclass_type: mnist

DATASET:
  subclass_type: mnist
  path: ABC
  train_batch_size: 256
  test_batch_size: 64

LOGGER:
  subclass_type: mnist
  project_name: trainer_code
  run_name: test1_mnist
  notes: testing trainer code with mnist

LOSS:
  reduction: sum

OPTIMIZER:
  lr: 0.005
  weight_decay: 0.0001

SCHEDULER:
  mode: min
  patience: 5

TEST:



